# Generated by Django 2.1.4 on 2018-12-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubeDeLeitura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'verbose_name': 'coleção', 'verbose_name_plural': 'coleções'},
        ),
    ]
